export const APP_BAR = 'RTAppBar';
export const AUTOCOMPLETE = 'RTAutocomplete';
export const AVATAR = 'RTAvatar';
export const BUTTON = 'RTButton';
export const CARD = 'RTCard';
export const CHIP = 'RTChip';
export const CHECKBOX = 'RTCheckbox';
export const DATE_PICKER = 'RTDatePicker';
export const DIALOG = 'RTDialog';
export const DROPDOWN = 'RTDropdown';
export const INPUT = 'RTInput';
export const LAYOUT = 'RTLayout';
export const LINK = 'RTLink';
export const LIST = 'RTList';
export const MENU = 'RTMenu';
export const NAVIGATION = 'RTNavigation';
export const OVERLAY = 'RTOverlay';
export const PROGRESS_BAR = 'RTProgressBar';
export const LOADER = 'RTLoader';
export const RADIO = 'RTRadio';
export const RIPPLE = 'RTRipple';
export const SLIDER = 'RTSlider';
export const SELECT_TYPE = 'RTSelect_type';
export const SELECT_TYPE_MEDCART = 'RTSelect_type_medcar';
export const SELECT_TYPE_DIARY_CHANGER = 'RTdiarychanger';
export const INPUTS_CHECKED_AND_SELECT = 'RTInputs_checked_and_select';
export const INPUTS_CHECKED_SURROUNDED = 'RTSurroundedCheck';
export const SCROLL_BAR = 'RTScrollbar';
export const SNACKBAR = 'RTSnackbar';
export const SWITCH = 'RTSwitch';
export const TABLE = 'RTTable';
export const TABS = 'RTTabs';
export const TOOLTIP = 'RTTooltip';
export const NOTIFICATION = 'RTNotification';
/*

var APP_BAR = exports.APP_BAR = 'RTAppBar';
var AUTOCOMPLETE = exports.AUTOCOMPLETE = 'RTAutocomplete';
var AVATAR = exports.AVATAR = 'RTAvatar';
var BUTTON = exports.BUTTON = 'RTButton';
var CARD = exports.CARD = 'RTCard';
var CHIP = exports.CHIP = 'RTChip';
var CHECKBOX = exports.CHECKBOX = 'RTCheckbox';
var DATE_PICKER = exports.DATE_PICKER = 'RTDatePicker';
var DIALOG = exports.DIALOG = 'RTDialog';
var DROPDOWN = exports.DROPDOWN = 'RTDropdown';
var INPUT = exports.INPUT = 'RTInput';
var LAYOUT = exports.LAYOUT = 'RTLayout';
var LINK = exports.LINK = 'RTLink';
var LIST = exports.LIST = 'RTList';
var MENU = exports.MENU = 'RTMenu';
var NAVIGATION = exports.NAVIGATION = 'RTNavigation';
var OVERLAY = exports.OVERLAY = 'RTOverlay';
var PROGRESS_BAR = exports.PROGRESS_BAR = 'RTProgressBar';
var RADIO = exports.RADIO = 'RTRadio';
var RIPPLE = exports.RIPPLE = 'RTRipple';
var SLIDER = exports.SLIDER = 'RTSlider';
var SNACKBAR = exports.SNACKBAR = 'RTSnackbar';
var SWITCH = exports.SWITCH = 'RTSwitch';
var TABLE = exports.TABLE = 'RTTable';
var TABS = exports.TABS = 'RTTabs';
var TOOLTIP = exports.TOOLTIP = 'RTTooltip';
var TIME_PICKER = exports.TIME_PICKER = 'RTTimePicker';
*/


